Mint/burn first handle Resubscribe and then finish Hub update
meTokens/meTokens-core pull request #189
Opened 2022-07-06 13:30 UTC by zgorizzo69

following tests to check the above change:
-> Mint: when resubscribing and updating- Poke or finish resubscribe should be called first and then finishUpdate.
-> Burn: when resubscribing and updating- Poke or finish resubscribe should be called first and then finishUpdate.
-> Burn: when resubscribing and updating- calculateActualAssetsReturned should calculate actualAssetsReturned with resubscribing formula.

2022-07-06 16:04 UTC, parv3213 approved these changes

2022-07-06 17:33 UTC, pegahcarter requested changes

2022-07-07 14:30 UTC, pegahcarter reviewed
Looks good. Found some additional outdated code to cleanup.

2022-07-12 21:24 UTC, pegahcarter approved these changes

2022-07-12 22:26 UTC, merged